### ISSUE TITLE
Penny Pitcher broken after 5.58 patch

### ISSUE THREAD

**Issue by RyanBlazee** [tesu/PennyPincher#14] opened 2021-07-20 15:09 UTC
I have removed and reinstalled the plugin but it is not responding.

**Comment by n3farious** [comment] 2021-07-20 16:21
Same issue. Additionally, tried to toggle all of the parameters to no avail.

**Comment by n3farious** [comment] 2021-07-20 20:53
> I have removed and reinstalled the plugin but it is not responding.

I just deleted my comment. See pinned issue #12, as this solves the problem. You may want to close your issue after verifying that the forced download fixes for you as well.

**Comment by Acederp** [comment] 2021-07-20 20:58
I have also have problems with penny pincher today. :petthetesu:

**Comment by tesu** [comment] 2021-07-20 21:16
dupe of #12

**Closed by tesu** 2021-07-20 21:16 UTC
