### ISSUE TITLE
Not copying

### ISSUE THREAD

**Issue by Polarthief** [tesu/PennyPincher#4] opened 2020-12-23 01:01 UTC
As of today (12/22) after the maintenance, Penny Pincher hasn't been working. I made sure it was enabled, not working, checked updates, no update was found for it

Sorry if this is a common thing after maintenance and whatnot; this is my first time using plugins, and my first issue with one post-hotfix/patch.

**Comment by tesu** [comment] 2020-12-23 05:38
Dupe of #2. Usually the opcodes get updated a while after the update drops (I've confirmed that they are working today).

**Closed by tesu** 2020-12-23 05:38 UTC
